table crawls
	lineageTag: 30059708-8959-405d-bf83-4beba3337794

	measure 'Total Crawls By Frequency' = COUNTROWS(crawls)
		formatString: #,0
		lineageTag: c0289c6c-5bd4-4832-9d92-f1992767b613

	column code
		dataType: string
		lineageTag: 3022072d-3e5a-4822-9c59-a4279f50b5be
		summarizeBy: none
		sourceColumn: code

		annotation SummarizationSetBy = Automatic

	column supply_chain_spider_id
		dataType: int64
		formatString: 0
		lineageTag: 8b105e75-a2ab-4459-98fe-c5841f0ca55c
		summarizeBy: none
		sourceColumn: supply_chain_spider_id

		annotation SummarizationSetBy = Automatic

	column tracking_number
		dataType: string
		lineageTag: 6f2c9b73-6e44-4efa-a48e-a20411d07481
		summarizeBy: none
		sourceColumn: tracking_number

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 9be8b0b8-f21f-4fa7-9e76-7bc767ee3ff0
		summarizeBy: none
		sourceColumn: created_at

		variation Variation
			isDefault
			relationship: fa82b557-db24-42c6-82db-a30d8c48a79f
			defaultHierarchy: LocalDateTable_feef3334-6970-41d5-af78-e8dffab61929.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column notes
		dataType: string
		lineageTag: e9addd50-3baf-4675-9823-5d9e8a6f9cf4
		summarizeBy: none
		sourceColumn: notes

		annotation SummarizationSetBy = Automatic

	column 'Tracking Time In Seconds'
		dataType: double
		lineageTag: ec86b566-8c39-465c-a4b3-ed573b45502f
		summarizeBy: sum
		sourceColumn: Tracking Time In Seconds

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crawl_status
		dataType: string
		lineageTag: 1585e8c2-87cd-45da-90f3-3a0ebfd49223
		summarizeBy: none
		sourceColumn: crawl_status

		annotation SummarizationSetBy = Automatic

	partition crawls = m
		mode: import
		source = ```
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"523c73c9-e8c6-4dc9-a68b-03117c0ff293" = Workspaces{[workspaceId="523c73c9-e8c6-4dc9-a68b-03117c0ff293"]}[Data],
				    #"b2d4b7bd-eb96-41d5-a024-aa53c13b0d55" = #"523c73c9-e8c6-4dc9-a68b-03117c0ff293"{[dataflowId="b2d4b7bd-eb96-41d5-a024-aa53c13b0d55"]}[Data],
				    crawls_ = #"b2d4b7bd-eb96-41d5-a024-aa53c13b0d55"{[entity="crawls",version=""]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(crawls_,{"id"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"code", type text}}),
				    #"Replaced Value of Code Column" = Table.ReplaceValue(#"Changed Type", each [code], each if [code]="0" then "ok" else if [code]="1" then "error" else if [code]="2" then "resolved" else [code],Replacer.ReplaceText,{"code"}),
				    #"Add Crawl Status Column" = Table.AddColumn(#"Replaced Value of Code Column", "crawl_status", each 
				    if [code] = "ok" and ([notes] = null or [notes] = "") then "ok" 
				    else if [code] = "error" then "code error" 
				    else if [code] = "ok" and ([notes] <> null or [notes] <> "") then "tracking error" 
				    else if [code] = "resolved" then "resolved" 
				    else [notes]
				)
				in
				    #"Add Crawl Status Column"
				```

	annotation PBI_ResultType = Table

