table node_level_documents
	lineageTag: 497158c8-4374-48f1-9db1-b532ac880eca

	measure 'Node Level Missing Count' = COUNT(node_level_documents[is_missing]) + 0
		formatString: 0
		lineageTag: df77c579-9316-4734-ac37-47937c1dc31a

	column 'Order Number'
		dataType: string
		lineageTag: 0d43901f-2818-437d-97f9-7ffcadc9bd2f
		summarizeBy: none
		sourceColumn: Order Number

		annotation SummarizationSetBy = Automatic

	column 'Reference Number'
		dataType: string
		lineageTag: a4ea8c3c-5c37-4cd4-bb83-529ebb9653bd
		summarizeBy: none
		sourceColumn: Reference Number

		annotation SummarizationSetBy = Automatic

	column 'Tracking Number'
		dataType: string
		lineageTag: c2476737-147f-490f-bb07-ad0bd601f230
		summarizeBy: none
		sourceColumn: Tracking Number

		annotation SummarizationSetBy = Automatic

	column Carrier
		dataType: string
		lineageTag: ea6175b6-326f-43b5-9b9e-4f6ab2dd59d4
		summarizeBy: none
		sourceColumn: Carrier

		annotation SummarizationSetBy = Automatic

	column 'Proof Of Delivery'
		dataType: string
		lineageTag: 444618f0-fce7-46b7-b124-811b3d8c60ea
		summarizeBy: none
		sourceColumn: Proof Of Delivery

		annotation SummarizationSetBy = Automatic

	column 'Commercial Invoice'
		dataType: string
		lineageTag: 3bfab949-38cc-4218-bce3-a4fb136eb771
		summarizeBy: none
		sourceColumn: Commercial Invoice

		annotation SummarizationSetBy = Automatic

	column 'Import Documents'
		dataType: string
		lineageTag: b8e27858-d0a6-441f-8235-0e94de5138c2
		summarizeBy: none
		sourceColumn: Import Documents

		annotation SummarizationSetBy = Automatic

	column 'Packing List'
		dataType: string
		lineageTag: 504c8d53-dc5a-479a-8312-4556702e0e70
		summarizeBy: none
		sourceColumn: Packing List

		annotation SummarizationSetBy = Automatic

	column 'Export Documents'
		dataType: string
		lineageTag: 01d0307b-ac46-4ebc-8f3e-88c817b0edd4
		summarizeBy: none
		sourceColumn: Export Documents

		annotation SummarizationSetBy = Automatic

	column 'Air Waybill'
		dataType: string
		lineageTag: f0b9ebd9-775d-462c-8463-8d842cd6a2d2
		summarizeBy: none
		sourceColumn: Air Waybill

		annotation SummarizationSetBy = Automatic

	column 'sftp_files.document_type'
		dataType: string
		lineageTag: 1875b89a-354e-4a2a-8de8-ae056565eead
		summarizeBy: none
		sourceColumn: sftp_files.document_type

		annotation SummarizationSetBy = Automatic

	column 'sftp_files.Index'
		dataType: int64
		formatString: 0
		lineageTag: 55738adc-2853-416b-bff5-f757ec9437b7
		summarizeBy: none
		sourceColumn: sftp_files.Index

		annotation SummarizationSetBy = Automatic

	column is_missing
		dataType: string
		lineageTag: 624b359f-5e6e-4a91-960d-af59db333058
		summarizeBy: none
		sourceColumn: is_missing

		annotation SummarizationSetBy = Automatic

	column ship_set_id
		dataType: int64
		formatString: 0
		lineageTag: ac71fc79-d5d0-42af-9dfc-ace2f6f8e213
		summarizeBy: sum
		sourceColumn: ship_set_id

		annotation SummarizationSetBy = Automatic

	column shipment_id
		dataType: int64
		formatString: 0
		lineageTag: 4ad36b4e-3b17-4c06-9645-bee8e62955e2
		summarizeBy: sum
		sourceColumn: shipment_id

		annotation SummarizationSetBy = Automatic

	column carrier_id
		dataType: int64
		formatString: 0
		lineageTag: f9286db8-ec6d-414d-b277-a3b417d6c923
		summarizeBy: none
		sourceColumn: carrier_id

		annotation SummarizationSetBy = Automatic

	partition node_level_documents = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"523c73c9-e8c6-4dc9-a68b-03117c0ff293" = Workspaces{[workspaceId="523c73c9-e8c6-4dc9-a68b-03117c0ff293"]}[Data],
				    #"c5a9e502-130c-4858-8bb6-00c11de8f806" = #"523c73c9-e8c6-4dc9-a68b-03117c0ff293"{[dataflowId="c5a9e502-130c-4858-8bb6-00c11de8f806"]}[Data],
				    node_level_documents_ = #"c5a9e502-130c-4858-8bb6-00c11de8f806"{[entity="node_level_documents",version=""]}[Data],
				    #"Merged Queries" = Table.NestedJoin(node_level_documents_, {"Tracking Number", "Carrier"}, sftp_files, {"shipment_identifier", "carrier"}, "sftp_files", JoinKind.LeftOuter),
				    #"Expanded sftp_files" = Table.ExpandTableColumn(#"Merged Queries", "sftp_files", {"document_type", "Index"}, {"sftp_files.document_type", "sftp_files.Index"}),
				    #"Added Conditional Column" = Table.AddColumn(
				                #"Expanded sftp_files",
				                "is_missing",
				                each
				                    if [sftp_files.document_type] = null then false
				                    else if [sftp_files.document_type] = "Air Waybill" and ([Air Waybill] = null or [Air Waybill] = "") then true
				                    else if [sftp_files.document_type] = "Commercial Invoice" and ([Commercial Invoice] = null or [Commercial Invoice] = "") then true
				                    else if [sftp_files.document_type] = "Packing List" and ([Packing List] = null or [Packing List] = "") then true
				                    else if [sftp_files.document_type] = "Proof Of Delivery" and ([Proof Of Delivery] = null or [Proof Of Delivery] = "") then true
				                    else if [sftp_files.document_type] = "Import Documents" and ([Import Documents] = null or [Import Documents] = "") then true
				                    else if [sftp_files.document_type] = "Export Documents" and ([Export Documents] = null or [Export Documents] = "") then true
				                    else false
				                )
				in
				    #"Added Conditional Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

