table order_level_documents
	lineageTag: 30ef8e3a-ecff-4120-8128-2e6d77d511ea

	measure 'Order Level Missing Count' = COUNT(order_level_documents[is_missing]) + 0
		formatString: 0
		lineageTag: f463a79f-7d5d-49f6-beb5-0e8771d3dfc5

	column 'Order Number'
		dataType: string
		lineageTag: 364ba7d1-fcb7-48ed-9e45-06e3bb855cf0
		summarizeBy: none
		sourceColumn: Order Number

		annotation SummarizationSetBy = Automatic

	column 'Reference Number'
		dataType: string
		lineageTag: ed9b489d-3b1e-46db-b553-e39e7d130677
		summarizeBy: none
		sourceColumn: Reference Number

		annotation SummarizationSetBy = Automatic

	column 'Tracking Number'
		dataType: string
		lineageTag: 9769a45d-d216-44ad-913e-c14d6d2542c1
		summarizeBy: none
		sourceColumn: Tracking Number

		annotation SummarizationSetBy = Automatic

	column Carrier
		dataType: string
		lineageTag: 50d52976-0653-423b-8b9d-a7b7c8f32c6b
		summarizeBy: none
		sourceColumn: Carrier

		annotation SummarizationSetBy = Automatic

	column 'Proof Of Delivery'
		dataType: string
		lineageTag: 627e046c-b739-4152-8dce-7769c4e07e2a
		summarizeBy: none
		sourceColumn: Proof Of Delivery

		annotation SummarizationSetBy = Automatic

	column 'Air Waybill'
		dataType: string
		lineageTag: 33de5086-1c40-4485-9223-116eb790d051
		summarizeBy: none
		sourceColumn: Air Waybill

		annotation SummarizationSetBy = Automatic

	column 'Commercial Invoice'
		dataType: string
		lineageTag: 33c8fede-34fa-4a73-af40-19bccc9a2071
		summarizeBy: none
		sourceColumn: Commercial Invoice

		annotation SummarizationSetBy = Automatic

	column 'Import Documents'
		dataType: string
		lineageTag: f807d014-9208-47fd-868d-24bda65c8bd0
		summarizeBy: none
		sourceColumn: Import Documents

		annotation SummarizationSetBy = Automatic

	column 'Packing List'
		dataType: string
		lineageTag: bced6a19-7896-4c6a-be63-5868152db356
		summarizeBy: none
		sourceColumn: Packing List

		annotation SummarizationSetBy = Automatic

	column 'Export Documents'
		dataType: string
		lineageTag: 280eb88a-c19e-4c0a-ba07-1b41faa34340
		summarizeBy: none
		sourceColumn: Export Documents

		annotation SummarizationSetBy = Automatic

	column 'sftp_files.document_type'
		dataType: string
		lineageTag: 1ba61af6-55bf-4d73-821d-be1cbb1297ad
		summarizeBy: none
		sourceColumn: sftp_files.document_type

		annotation SummarizationSetBy = Automatic

	column 'sftp_files.Index'
		dataType: int64
		formatString: 0
		lineageTag: 7293753b-1905-4ebc-9647-c82df016d867
		summarizeBy: none
		sourceColumn: sftp_files.Index

		annotation SummarizationSetBy = Automatic

	column is_missing
		dataType: string
		lineageTag: dad828f4-d08e-40f4-b19a-30f277cf936f
		summarizeBy: none
		sourceColumn: is_missing

		annotation SummarizationSetBy = Automatic

	column ship_set_id
		dataType: int64
		formatString: 0
		lineageTag: 1110b715-8546-4667-9acd-2648be7b6135
		summarizeBy: sum
		sourceColumn: ship_set_id

		annotation SummarizationSetBy = Automatic

	column shipment_id
		dataType: int64
		formatString: 0
		lineageTag: 563b885f-ca0a-4814-a438-55979ffa407d
		summarizeBy: sum
		sourceColumn: shipment_id

		annotation SummarizationSetBy = Automatic

	column carrier_id
		dataType: int64
		formatString: 0
		lineageTag: de75ce53-14bd-4ed7-83f9-263619e5c44b
		summarizeBy: none
		sourceColumn: carrier_id

		annotation SummarizationSetBy = Automatic

	partition order_level_documents = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"523c73c9-e8c6-4dc9-a68b-03117c0ff293" = Workspaces{[workspaceId="523c73c9-e8c6-4dc9-a68b-03117c0ff293"]}[Data],
				    #"c5a9e502-130c-4858-8bb6-00c11de8f806" = #"523c73c9-e8c6-4dc9-a68b-03117c0ff293"{[dataflowId="c5a9e502-130c-4858-8bb6-00c11de8f806"]}[Data],
				    order_level_documents_ = #"c5a9e502-130c-4858-8bb6-00c11de8f806"{[entity="order_level_documents",version=""]}[Data],
				    #"Merged Queries" = Table.NestedJoin(order_level_documents_, {"Tracking Number", "Carrier"}, sftp_files, {"shipment_identifier", "carrier"}, "sftp_files", JoinKind.LeftOuter),
				    #"Expanded sftp_files" = Table.ExpandTableColumn(#"Merged Queries", "sftp_files", {"document_type", "Index"}, {"sftp_files.document_type", "sftp_files.Index"}),
				    #"Added Conditional Column" = Table.AddColumn(
				                #"Expanded sftp_files",
				                "is_missing",
				                each
				                    if [sftp_files.document_type] = null then false
				                    else if [sftp_files.document_type] = "Air Waybill" and ([Air Waybill] = null or [Air Waybill] = "") then true
				                    else if [sftp_files.document_type] = "Commercial Invoice" and ([Commercial Invoice] = null or [Commercial Invoice] = "") then true
				                    else if [sftp_files.document_type] = "Packing List" and ([Packing List] = null or [Packing List] = "") then true
				                    else if [sftp_files.document_type] = "Proof Of Delivery" and ([Proof Of Delivery] = null or [Proof Of Delivery] = "") then true
				                    else if [sftp_files.document_type] = "Import Documents" and ([Import Documents] = null or [Import Documents] = "") then true
				                    else if [sftp_files.document_type] = "Export Documents" and ([Export Documents] = null or [Export Documents] = "") then true
				                    else false
				                )
				in
				    #"Added Conditional Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

