table sftp_files
	lineageTag: 4040c474-5a8f-42fb-8fe8-e65e51b89d34

	column shipment_identifier
		dataType: string
		lineageTag: 335e38e2-2774-4256-8c2e-6b65726f9436
		summarizeBy: none
		sourceColumn: shipment_identifier

		annotation SummarizationSetBy = Automatic

	column carrier
		dataType: string
		lineageTag: 1de2a4da-ed45-4368-aafc-6e8f8617031f
		summarizeBy: none
		sourceColumn: carrier

		annotation SummarizationSetBy = Automatic

	column document_type
		dataType: string
		lineageTag: b65d592c-a132-4d1c-b7dd-2b1a9ea70ca6
		summarizeBy: none
		sourceColumn: document_type

		annotation SummarizationSetBy = Automatic

	column file_path
		dataType: string
		lineageTag: fe15d392-4fd9-4840-8e03-1e40ecb5da83
		summarizeBy: none
		sourceColumn: file_path

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 50d3c543-3a83-4391-b7bf-a0a759f8bdf4
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition sftp_files = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"523c73c9-e8c6-4dc9-a68b-03117c0ff293" = Workspaces{[workspaceId="523c73c9-e8c6-4dc9-a68b-03117c0ff293"]}[Data],
				    #"41c0cef4-a4e8-4e9e-83db-ee8488138e83" = #"523c73c9-e8c6-4dc9-a68b-03117c0ff293"{[dataflowId="41c0cef4-a4e8-4e9e-83db-ee8488138e83"]}[Data],
				    sftp_files_ = #"41c0cef4-a4e8-4e9e-83db-ee8488138e83"{[entity="sftp_files",version=""]}[Data],
				    #"Added Index" = Table.AddIndexColumn(sftp_files_, "Index", 1, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

